### ISSUE TITLE
"input_image" placeholder not found in graph

### ISSUE THREAD

**Issue by nishithbsk** [vsoch/boneage#1]
Hi Vanessa and Matt,

I'm trying to run a forward pass on the network after loading in the meta and checkpoint files. To do so, I need to construct a `feed_dict` containing `input_image` (as defined [here](https://github.com/vsoch/boneage/blob/master/boneage/resnet.py#L41)). However, I'm unable to find the placeholder `input_image` in the graph. Any thoughts?

Steps to reproduce:
```
import tensorflow as tf
saver = tf.train.import_meta_graph("./bone-age-checkpoint.ckpt-19999.meta")
graph = tf.get_default_graph()
nodes = graph.as_graph_def().node # this returns a list of all nodes in the graph
for node in nodes:
    if "input_image" in node.name:
       print node # it never reaches here
```
Thanks a lot for the help!

**Comment by vsoch** [comment]
I can't comment because I didn't make the original model, but I think @mchen17 might have some insight.

**Comment by vsoch** [comment]
And I hope you saw this! --> http://rsnachallenges.cloudapp.net/competitions/4

**Comment by mchen17** [comment]
I suspect it is an issue with reconstructing the graph using the meta file. This looks like a similar problem

https://stackoverflow.com/questions/44251328/tensorflow-print-all-placeholder-variable-names-from-meta-graph

You might have better luck just reconstructing the graph with the given code and using saver to restore the weights once the computational graph has been initialized.

**Comment by nishithbsk** [comment]
Thanks @mchen17 and @vsoch. Upgrading some functions to TF 1.0+ and saving the meta graph again resolved this issue!
